name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        name: id_ed25519

    - name: Debug SSH
      run: |
        ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
        ssh -v ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'echo "SSH connection successful"'

    - name: Install sshpass
      run: sudo apt-get install sshpass

    - name: Deploy with rsync
      run: |
        sshpass -p ${{ secrets.SSH_PASSWORD }} rsync -avz -e "ssh -o StrictHostKeyChecking=no" --delete ./ ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.PROJECT_PATH }}

    - name: Execute remote SSH commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ${{ secrets.PROJECT_PATH }}
          docker compose down
          docker compose up -d --build
